[build]
  publish = "build"
  command = """
    raco pkg config --set catalogs \
      "https://download.racket-lang.org/releases/8.4/catalog/" \
      "https://pkg-build.racket-lang.org/server/built/catalog/" \
      "https://pkgs.racket-lang.org" \
      "https://planet-compats.racket-lang.org" &&
    raco pkg install --binary --no-docs --auto pollen  &&
    mkdir build &&
    raco pollen render src
    raco pollen publish src build
  """

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
[build.processing.js]
  bundle = false
  minify = false
