[build]
  publish = "build"
  command = """
    raco pkg install --auto pollen &&
    mkdir build &&
    raco pollen publish build
  """

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
[build.processing.js]
  bundle = false
  minify = false
